package com.minimont.ui

import android.annotation.SuppressLint
import android.content.Context
import android.graphics.PixelFormat
import android.hardware.display.DisplayManager
import android.view.Display
import android.util.Log
import android.view.Gravity
import android.view.View
import android.view.WindowManager
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.platform.ComposeView
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleOwner
import androidx.lifecycle.LifecycleRegistry
import androidx.lifecycle.ViewModelStore
import androidx.lifecycle.ViewModelStoreOwner
import androidx.lifecycle.setViewTreeLifecycleOwner
import androidx.lifecycle.setViewTreeViewModelStoreOwner
import androidx.savedstate.SavedStateRegistry
import androidx.savedstate.SavedStateRegistryController
import androidx.savedstate.SavedStateRegistryOwner
import androidx.savedstate.setViewTreeSavedStateRegistryOwner
import com.minimont.MontAccessibilityService
import com.minimont.ui.mont.Mont
import com.minimont.ui.mont.MontSurface
import com.minimont.ui.mont.MontWhite

/**
 * The pairing strip, floated over Android's own wireless debugging screen.
 *
 * The six-digit code is generated by Settings and shown in a Settings dialog. Sending the user
 * there to read it means leaving this app, so the field they type it into has to travel with them.
 * This is that field: an accessibility overlay pinned to the bottom of the screen, with Android's
 * dialog still readable above it.
 *
 * It is deliberately one line. The whole reason for floating it is that the code stays visible, and
 * a panel that fills the screen defeats that.
 */
object PairingOverlay {
    private var windowManager: WindowManager? = null
    private var view: View? = null
    private var owner: OverlayOwner? = null

    val showing: Boolean get() = view != null

    /**
     * A window that is not an activity still has to answer the three owners Compose looks for on
     * the view tree, or `ComposeView` refuses to compose into it.
     */
    private class OverlayOwner : LifecycleOwner, ViewModelStoreOwner, SavedStateRegistryOwner {
        private val registry = LifecycleRegistry(this)
        private val savedState = SavedStateRegistryController.create(this)
        override val lifecycle: Lifecycle get() = registry
        override val viewModelStore = ViewModelStore()
        override val savedStateRegistry: SavedStateRegistry get() = savedState.savedStateRegistry

        fun create() {
            savedState.performRestore(null)
            registry.currentState = Lifecycle.State.RESUMED
        }

        fun destroy() {
            registry.currentState = Lifecycle.State.DESTROYED
            viewModelStore.clear()
        }
    }

    /**
     * Float the strip on a named display.
     *
     * @return null when it is up, or a sentence saying why it is not.
     *
     * The display has to be named. A folded Flip is showing its cover screen, which is a different
     * display from the one an accessibility service defaults to — a window added to the default
     * display there is a window nobody can see, on a screen that is switched off.
     */
    @SuppressLint("ClickableViewAccessibility")
    fun show(displayId: Int, content: @Composable () -> Unit): String? {
        hide()
        val service = MontAccessibilityService.instance
            ?: return "miniMont's accessibility service is not running."
        return runCatching {
            val type = WindowManager.LayoutParams.TYPE_ACCESSIBILITY_OVERLAY
            val displays = service.getSystemService(Context.DISPLAY_SERVICE) as DisplayManager
            val display = displays.getDisplay(displayId)
                ?: displays.getDisplay(Display.DEFAULT_DISPLAY)
            // A window context has to be built from a display context. Asking the service for one
            // directly gets a window on whichever display it happens to think it is on.
            val windowContext = service.createDisplayContext(display).createWindowContext(type, null)
            val manager = windowContext.getSystemService(Context.WINDOW_SERVICE) as WindowManager

            val overlayOwner = OverlayOwner().apply { create() }
            val composeView = ComposeView(windowContext).apply {
                setViewTreeLifecycleOwner(overlayOwner)
                setViewTreeViewModelStoreOwner(overlayOwner)
                setViewTreeSavedStateRegistryOwner(overlayOwner)
                setContent(content)
            }

            val params = WindowManager.LayoutParams(
                WindowManager.LayoutParams.MATCH_PARENT,
                WindowManager.LayoutParams.WRAP_CONTENT,
                type,
                // Focusable so it can be typed into, but not touch-modal, so every tap outside it
                // still reaches the Settings screen behind. Without that the strip owns the whole
                // display and the dialog it is floating over cannot be used at all.
                WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL or
                    WindowManager.LayoutParams.FLAG_WATCH_OUTSIDE_TOUCH,
                PixelFormat.TRANSLUCENT
            ).apply {
                // Top, not bottom. Android draws the six digits low on the screen, so a strip
                // held to the bottom lands directly on the one thing it exists to let you read.
                gravity = Gravity.TOP or Gravity.START
                // It is typed into, so it has to ride above the keyboard rather than under it.
                softInputMode = WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE
                title = "miniMont pairing"
            }

            manager.addView(composeView, params)
            windowManager = manager
            view = composeView
            owner = overlayOwner
            Log.i(TAG, "pairing strip floated on display $displayId")
            null
        }.getOrElse { failure ->
            // Reported rather than swallowed. A strip that silently fails to appear looks exactly
            // like one that appeared on a screen you are not looking at.
            Log.e(TAG, "could not float the pairing strip", failure)
            failure.message ?: failure.javaClass.simpleName
        }
    }

    fun hide() {
        view?.let { runCatching { windowManager?.removeViewImmediate(it) } }
        owner?.destroy()
        view = null
        windowManager = null
        owner = null
    }

    private const val TAG = "miniMont.Pairing"
}

/**
 * The strip itself: a status line, the port, the code, and the two commitments.
 *
 * The port is filled in from mDNS and is only ever typed when discovery has failed, which is why it
 * is the narrow field and the code is the wide one.
 */
@Composable
fun PairingStrip(
    code: String,
    port: String,
    discoveredPort: Int?,
    status: String,
    busy: Boolean,
    onCode: (String) -> Unit,
    onPort: (String) -> Unit,
    onPair: () -> Unit,
    onClose: () -> Unit,
    modifier: Modifier = Modifier
) {
    val effectivePort = port.ifBlank { discoveredPort?.toString().orEmpty() }
    val canPair = !busy && code.length == 6 && effectivePort.isNotBlank()

    Column(
        modifier
            .fillMaxWidth()
            .background(MontSurface)
            .padding(start = 22.dp, top = 8.dp, end = 14.dp, bottom = 10.dp),
        verticalArrangement = Arrangement.spacedBy(4.dp)
    ) {
        Text(
            text = status.uppercase(),
            color = Color.White.copy(alpha = MontWhite.DETAIL),
            fontFamily = Mont,
            fontWeight = FontWeight.Black,
            fontSize = 9.sp,
            letterSpacing = 0.5.sp,
            maxLines = 1
        )
        Row(
            Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Field(port, discoveredPort?.toString() ?: "PORT", onPort, Modifier.width(72.dp))
            Field(code, "CODE", onCode, Modifier.weight(1f))
            Text(
                text = "PAIR",
                color = Color.White.copy(if (canPair) MontWhite.ACTIVE else MontWhite.DISABLED),
                fontFamily = Mont,
                fontWeight = FontWeight.Black,
                fontSize = 14.sp,
                modifier = Modifier
                    .clickable(enabled = canPair, onClick = onPair)
                    .padding(horizontal = 6.dp, vertical = 7.dp)
            )
            Text(
                text = "CLOSE",
                color = Color.White.copy(MontWhite.DIM),
                fontFamily = Mont,
                fontWeight = FontWeight.Black,
                fontSize = 11.sp,
                letterSpacing = 0.5.sp,
                modifier = Modifier
                    .clickable(onClick = onClose)
                    .padding(horizontal = 4.dp, vertical = 7.dp)
            )
        }
    }
}

/**
 * A field is a white block with black type — the same filled rectangle the toggle uses for its
 * live half. No outline, no corner, no label above it.
 */
@Composable
private fun Field(
    value: String,
    placeholder: String,
    onValue: (String) -> Unit,
    modifier: Modifier = Modifier
) {
    Box(
        modifier
            .height(32.dp)
            .background(Color.White)
            .padding(horizontal = 8.dp),
        contentAlignment = Alignment.CenterStart
    ) {
        BasicTextField(
            value = value,
            onValueChange = onValue,
            singleLine = true,
            textStyle = TextStyle(
                color = Color.Black,
                fontFamily = Mont,
                fontWeight = FontWeight.Black,
                fontSize = 15.sp,
                letterSpacing = 2.sp
            ),
            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
            cursorBrush = SolidColor(Color.Black),
            modifier = Modifier.fillMaxWidth()
        )
        if (value.isEmpty()) {
            Text(
                text = placeholder,
                color = Color.Black.copy(alpha = 0.35f),
                fontFamily = Mont,
                fontWeight = FontWeight.Black,
                fontSize = 11.sp,
                letterSpacing = 0.5.sp
            )
        }
    }
}
